create table if not exists public.concrete_inventory_stock_adjustments (
  id bigint generated by default as identity primary key,
  branch_id bigint not null references public.branches(id) on delete cascade,
  product_id bigint not null references public.concrete_products(id) on delete cascade,
  previous_qty_base numeric not null default 0,
  new_qty_base numeric not null default 0,
  delta_qty_base numeric not null default 0,
  reason text,
  notes text,
  created_by text,
  created_at timestamp with time zone not null default now()
);

create index if not exists concrete_inventory_stock_adjustments_branch_product_created_idx
  on public.concrete_inventory_stock_adjustments (branch_id, product_id, created_at desc);

alter table public.concrete_inventory_stock_adjustments disable row level security;

grant select on public.concrete_inventory_stock_adjustments to anon, authenticated;
grant all on public.concrete_inventory_stock_adjustments to service_role;
grant usage, select on sequence public.concrete_inventory_stock_adjustments_id_seq to anon, authenticated, service_role;

create or replace function public.adjust_concrete_inventory_stock(
  p_branch_id bigint,
  p_product_id bigint,
  p_new_qty_base numeric,
  p_reason text default null,
  p_notes text default null,
  p_created_by text default null
)
returns table (
  previous_qty_base numeric,
  new_qty_base numeric,
  delta_qty_base numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous_qty numeric := 0;
  v_delta_qty numeric := 0;
  v_has_stock_column boolean := false;
begin
  if p_branch_id is null or p_product_id is null then
    raise exception 'Sucursal o producto inválido.';
  end if;

  if p_new_qty_base is null or p_new_qty_base < 0 then
    raise exception 'El nuevo stock debe ser mayor o igual a 0.';
  end if;

  insert into public.concrete_inventory_stock (branch_id, product_id, qty_base, updated_at)
  values (p_branch_id, p_product_id, 0, now())
  on conflict (branch_id, product_id) do nothing;

  select qty_base
    into v_previous_qty
  from public.concrete_inventory_stock
  where branch_id = p_branch_id
    and product_id = p_product_id
  for update;

  v_previous_qty := coalesce(v_previous_qty, 0);
  v_delta_qty := p_new_qty_base - v_previous_qty;

  update public.concrete_inventory_stock
  set qty_base = p_new_qty_base,
      updated_at = now()
  where branch_id = p_branch_id
    and product_id = p_product_id;

  insert into public.concrete_inventory_stock_adjustments (
    branch_id,
    product_id,
    previous_qty_base,
    new_qty_base,
    delta_qty_base,
    reason,
    notes,
    created_by
  )
  values (
    p_branch_id,
    p_product_id,
    v_previous_qty,
    p_new_qty_base,
    v_delta_qty,
    nullif(trim(coalesce(p_reason, '')), ''),
    nullif(trim(coalesce(p_notes, '')), ''),
    nullif(trim(coalesce(p_created_by, '')), '')
  );

  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'concrete_products'
      and column_name = 'stock'
  )
  into v_has_stock_column;

  if v_has_stock_column then
    execute '
      update public.concrete_products
      set stock = $1,
          updated_at = now()
      where id = $2
    '
    using p_new_qty_base, p_product_id;
  else
    update public.concrete_products
    set updated_at = now()
    where id = p_product_id;
  end if;

  return query
  select v_previous_qty, p_new_qty_base, v_delta_qty;
end;
$$;

grant execute on function public.adjust_concrete_inventory_stock(bigint, bigint, numeric, text, text, text)
  to anon, authenticated, service_role;
